### ISSUE TITLE
QR code broken

### ISSUE THREAD

**Issue by pille** [tomster/halfnarp#27]
the QR code i got from my selection was unreadable by my mobile scanner (zxing). there may be various reasons:
1) it contained lots of data (224x224 pixel for about 80 events).
2) there is no quiet zone in the picture itself. that makes scaling inside the browser a pain. adding one manually didn't made it readable.
3) it seems wrong: the (small) marker patterns have a different pixel size. some are not even square.
4) lots or random UPC 1-D codes are recognized.
5) on that scale my camera has a slight fish-eye effect and straight lines are slightly curved.

maybe it's better to generate a link to the data, instead of embedding the whole data itself.

**Comment by erdgeist** [comment]
Fixed in f78b895b0e5a213edaa04a37ed6876162de08806.

**Comment by pille** [comment]
works, when i manually add a white quite zone around the newly generated image.
can you please implement that?

**Comment by erdgeist** [comment]
Would you please mind reloading? And if this doesn't work, just paste a diff to the css.

**Comment by pille** [comment]
works now as expected.
